server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clicker
    username: postgres
    password: postgres
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update